uCommerceSiteDev/uCommerceSiteDev/Controllers/CategoryTabController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using uCommerceSiteDev.Models;
using UCommerce.Api;
using UCommerce.Content;
using UCommerce.EntitiesV2;
using UCommerce.Extensions;
using UCommerce.Infrastructure;
using UCommerce.Runtime;
using Umbraco.Web.Mvc;

namespace uCommerceSiteDev.Controllers
{
    public class CategoryTabController : SurfaceController
    {
        // GET: CategoryTab
        public ActionResult Index()
        {
            CategoryNavigationViewModel categoryNavigationViewModel = new CategoryNavigationViewModel();
            categoryNavigationViewModel.Categories = this.MapCategories(CatalogLibrary.GetRootCategories());
            return View("/views/CategoryTab.cshtml", categoryNavigationViewModel);
        }

        private IList<CategoryViewModel> MapCategories(ICollection<Category> categoriesToMap)
        {
            IList<CategoryViewModel> categoryViewModels = new List<CategoryViewModel>();
            foreach (Category category in categoriesToMap)
            {
                List<ProductViewModel> productList = new List<ProductViewModel>();

                IEnumerable<Product> products = SiteContext.Current.CatalogContext.CurrentCatalog.Categories.SelectMany<Category, Product>((Category c) =>
                    from p in c.Products
                    where p.GetCategories().Contains(category)
                    select p).Distinct();
                foreach (var product in products)
                {
                    productList.Add(new ProductViewModel
                    {
                        Name = product.Name,
                        PriceCalculation = CatalogLibrary.CalculatePrice(product, null),
                        Url = CatalogLibrary.GetNiceUrlForProduct(product, null, null),
                        Sku = product.Sku,
                        IsVariant = product.IsVariant,
                        VariantSku = product.VariantSku,
                        ThumbnailImageUrl = ObjectFactory.Instance.Resolve<IImageService>().GetImage(product.ThumbnailImageMediaId).Url
                    });
                }

                CategoryViewModel categoryViewModel = new CategoryViewModel()
                {
                    Name = CategoryExtensions.DisplayName(category),
                    Url = CatalogLibrary.GetNiceUrlForCategory(category, null),
                    Categories = null,
                    Products = productList
                };
                categoryViewModels.Add(categoryViewModel);
            }
            return categoryViewModels;
        }
    }
}

uCommerceSiteDev/uCommerceSiteDev/Controllers/FeatureItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using uCommerceSiteDev.Common;
using uCommerceSiteDev.Models;
using UCommerce.Api;
using UCommerce.Content;
using UCommerce.EntitiesV2;
using UCommerce.Extensions;
using UCommerce.Infrastructure;
using UCommerce.Runtime;
using Umbraco.Web.Mvc;

namespace uCommerceSiteDev.Controllers
{
    public class FeatureItemController : SurfaceController
    {
        // GET: FeatureItem
        public ActionResult Index()
        {
            //IEnumerable<Product> products = SiteContext.Current.CatalogContext.CurrentCatalog.Categories.SelectMany<Category, Product>((Category c) =>
            //    from p in c.Products
            //    where p.ProductProperties.Any<ProductProperty>((ProductProperty pp) =>
            //    {
            //        if (pp.ProductDefinitionField.Name != "ShowOnHomepage")
            //        {
            //            return false;
            //        }
            //        return Convert.ToBoolean(pp.Value);
            //    })
            //    select p);

            IEnumerable<Product> products =
                SiteContext.Current.CatalogContext.CurrentCatalog.Categories.SelectMany<Category, Product>(
                    (Category c) =>
                        from p in c.Products select p).Distinct();
            ProductsViewModel productsViewModel = new ProductsViewModel();
            foreach (Product product in products)
            {
                productsViewModel.Products.Add(new ProductViewModel()
                {
                    Name = product.Name,
                    PriceCalculation = CatalogLibrary.CalculatePrice(product, null),
                    Url = CatalogLibrary.GetNiceUrlForProduct(product, null, null),
                    Sku = product.Sku,
                    IsVariant = product.IsVariant,
                    VariantSku = product.VariantSku,
                    ThumbnailImageUrl = UnitHelper.PrimaryImageMediaIdToUrl(product.ThumbnailImageMediaId)
                });

                //var images = product.GetPropertyValue<string>("Images");
                //if (!string.IsNullOrEmpty(images))
                //{
                //    foreach (var image in product.GetPropertyValue<string>("Images").Split(';'))
                //    {
                //        var test = image;
                //    }
                //}
            }
            return View("/Views/FeatureItem.cshtml", productsViewModel);
        }
    }
}

uCommerceSiteDev/uCommerceSiteDev/Views/MacroPartials/Brands_Products.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

<h2>Brands</h2>
<div class="brands-name">
    <ul class="nav nav-pills nav-stacked">
        <li><a href="#"> <span class="pull-right">(50)</span>Acne</a></li>
        <li><a href="#"> <span class="pull-right">(56)</span>Grüne Erde</a></li>
        <li><a href="#"> <span class="pull-right">(27)</span>Albiro</a></li>
        <li><a href="#"> <span class="pull-right">(32)</span>Ronhill</a></li>
        <li><a href="#"> <span class="pull-right">(5)</span>Oddmolly</a></li>
        <li><a href="#"> <span class="pull-right">(9)</span>Boudestijn</a></li>
        <li><a href="#"> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
    </ul>
</div>

uCommerceSiteDev/uCommerceSiteDev/Views/MacroPartials/Category_Products.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{Html.RenderAction("Index", "Navigation"); }

uCommerceSiteDev/uCommerceSiteDev/Views/MacroPartials/Category_Tab.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{Html.RenderAction("Index", "CategoryTab"); }

uCommerceSiteDev/uCommerceSiteDev/Views/MacroPartials/Feature_Item.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

 @{ Html.RenderAction("Index", "FeatureItem"); }

uCommerceSiteDev/uCommerceSiteDev/Views/MacroPartials/Footer.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

<div class="footer-top">
    <div class="container">
        <div class="row">
            <div class="col-sm-2">
                <div class="companyinfo">
                    <h2><span>e</span>-shopper</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
                </div>
            </div>
            <div class="col-sm-7">
                <div class="col-sm-3">
                    <div class="video-gallery text-center">
                        <a href="#">
                            <div class="iframe-img">
                                <img src="~/images/home/iframe1.png" alt="" />
                            </div>
                            <div class="overlay-icon">
                                <i class="fa fa-play-circle-o"></i>
                            </div>
                        </a>
                        <p>Circle of Hands</p>
                        <h2>24 DEC 2014</h2>
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="video-gallery text-center">
                        <a href="#">
                            <div class="iframe-img">
                                <img src="~/images/home/iframe2.png" alt="" />
                            </div>
                            <div class="overlay-icon">
                                <i class="fa fa-play-circle-o"></i>
                            </div>
                        </a>
                        <p>Circle of Hands</p>
                        <h2>24 DEC 2014</h2>
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="video-gallery text-center">
                        <a href="#">
                            <div class="iframe-img">
                                <img src="~/images/home/iframe3.png" alt="" />
                            </div>
                            <div class="overlay-icon">
                                <i class="fa fa-play-circle-o"></i>
                            </div>
                        </a>
                        <p>Circle of Hands</p>
                        <h2>24 DEC 2014</h2>
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="video-gallery text-center">
                        <a href="#">
                            <div class="iframe-img">
                                <img src="~/images/home/iframe4.png" alt="" />
                            </div>
                            <div class="overlay-icon">
                                <i class="fa fa-play-circle-o"></i>
                            </div>
                        </a>
                        <p>Circle of Hands</p>
                        <h2>24 DEC 2014</h2>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="address">
                    <img src="~/images/home/map.png" alt="" />
                    <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="footer-widget">
    <div class="container">
        <div class="row">
            <div class="col-sm-2">
                <div class="single-widget">
                    <h2>Service</h2>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#">Online Help</a></li>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Order Status</a></li>
                        <li><a href="#">Change Location</a></li>
                        <li><a href="#">FAQ’s</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="single-widget">
                    <h2>Quock Shop</h2>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#">T-Shirt</a></li>
                        <li><a href="#">Mens</a></li>
                        <li><a href="#">Womens</a></li>
                        <li><a href="#">Gift Cards</a></li>
                        <li><a href="#">Shoes</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="single-widget">
                    <h2>Policies</h2>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Privecy Policy</a></li>
                        <li><a href="#">Refund Policy</a></li>
                        <li><a href="#">Billing System</a></li>
                        <li><a href="#">Ticket System</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="single-widget">
                    <h2>About Shopper</h2>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#">Company Information</a></li>
                        <li><a href="#">Careers</a></li>
                        <li><a href="#">Store Location</a></li>
                        <li><a href="#">Affillate Program</a></li>
                        <li><a href="#">Copyright</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-3 col-sm-offset-1">
                <div class="single-widget">
                    <h2>About Shopper</h2>
                    <form action="#" class="searchform">
                        <input type="text" placeholder="Your email address" />
                        <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                        <p>Get the most recent updates from <br />our site and be updated your self...</p>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="footer-bottom">
    <div class="container">
        <div class="row">
            <p class="pull-left">@Umbraco.Field("copyright", recursive: true)</p>
            <p class="pull-right">Designed by <span><a target="_blank" href="@Umbraco.Field("urlDesign", recursive: true)">>@Umbraco.Field("designBy", recursive: true)</a></span></p>
        </div>
    </div>
</div>

uCommerceSiteDev/uCommerceSiteDev/Views/MacroPartials/Header.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
    var root = CurrentPage.AncestorsOrSelf(1).First();
    var basket = root.Children.Where("DocumentTypeAlias ==\"basket\"").First();
}
<header id="header">
    <!--header-->
    <div class="header_top">
        <!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->
    <div class="header-middle">
        <!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="logo pull-left">
                        <a href="@root.Url"><img src="~/images/home/logo.png" alt="" /></a>
                    </div>
                    <div class="btn-group pull-right">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                USA
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canada</a></li>
                                <li><a href="#">UK</a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                DOLLAR
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canadian Dollar</a></li>
                                <li><a href="#">Pound</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="shop-menu pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-user"></i> Account</a></li>
                            <li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li>
                            @*<li><a href="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>*@
                            <li><a href="@basket.Url"><i class="fa fa-shopping-cart"></i> Cart</a></li>
                            @*<li><a href="login.html"><i class="fa fa-lock"></i> Login</a></li>*@
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->
    <div class="header-bottom">
        <!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li><a href="@root.Url" class="active">Home</a></li>
                            @*<li class="dropdown">
                                    <a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="shop.html">Products</a></li>
                                        <li><a href="product-details.html">Product Details</a></li>
                                        <li><a href="checkout.html">Checkout</a></li>
                                        <li><a href="cart.html">Cart</a></li>
                                        <li><a href="login.html">Login</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#">Blog<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="blog.html">Blog List</a></li>
                                        <li><a href="blog-single.html">Blog Single</a></li>
                                    </ul>
                                </li>
                                <li><a href="404.html">404</a></li>*@
                            <li><a href="contact-us.html">Contact</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="Search" />
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

uCommerceSiteDev/uCommerceSiteDev/Views/MacroPartials/Meta_Head.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<title>Home | E-Shopper</title>
<link href="~/css/bootstrap.min.css" rel="stylesheet">
<link href="~/css/font-awesome.min.css" rel="stylesheet">
<link href="~/css/prettyPhoto.css" rel="stylesheet">
<link href="~/css/price-range.css" rel="stylesheet">
<link href="~/css/animate.css" rel="stylesheet">
<link href="~/css/main.css" rel="stylesheet">
<link href="~/css/responsive.css" rel="stylesheet">
<link rel="shortcut icon" href="images/ico/favicon.ico">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/images/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/images/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/images/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="~/images/ico/apple-touch-icon-57-precomposed.png">

uCommerceSiteDev/uCommerceSiteDev/Views/MacroPartials/Slider.cshtml
@using UCommerce.Xslt
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
    var root = CurrentPage.AncestorsOrSelf(1).First();
    var imageSlider = root.Children.Where("DocumentTypeAlias == @0", "slider");
    var listSlider = imageSlider.First().Children;
    var isHomePage = root == CurrentPage ? true : false;
}

@if (isHomePage)
{
    <section id="slider">
        <!--slider-->
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div id="slider-carousel" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            @for (int i = 0; i < listSlider.Count(); i++)
                            {
                                <li data-target="#slider-carousel" data-slide-to="@i" class="@(i==0?"active":"")"></li>
                            }
                            @*<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
                                <li data-target="#slider-carousel" data-slide-to="1"></li>
                                <li data-target="#slider-carousel" data-slide-to="2"></li>*@
                        </ol>
                        <div class="carousel-inner">
                            @if (listSlider.Any())
                            {
                                foreach (var item in listSlider)
                                {
                                    <div class="item @(item == listSlider[0] ? "active" : "" )">
                                        <div class="col-sm-6">
                                            <h1>@Umbraco.Field("siteName", recursive: true)</h1>
                                            <h2>@item.title</h2>
                                            <p>@item.description</p>
                                            <button type="button" class="btn btn-default get">Get it now</button>
                                        </div>
                                        <div class="col-sm-6">
                                            <img src="@Umbraco.Media(item.introduce).url" class="girl img-responsive" alt="" />
                                            <img src="@Umbraco.Media(item.priceLogo).url" class="pricing" alt="" />
                                        </div>
                                    </div>
                                }
                            }
                        </div>
                        <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
                            <i class="fa fa-angle-left"></i>
                        </a>
                        <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section><!--/slider-->
}